## Part 3: Feature Engineering

The goal of this notebook is to generate features for use in training predictive models using variables contained in the dataset. 

This will involve: 
- Regularizing features so that they are all roughly the same magnitude.
- Calculating the percent change of any features that have a strong trend over time. For these types of features, the magnitude of the change from month to month can have very different importance depending on its current value. For example, QQQ increasing from $1 to $2 is much more interesting than it increasing from $100 to $101.
- Defining the target variables for various predictors I want to train. 
    - In the case of defining market health, I will consider two target variables:
        - the GDP next quarter
        - the GDP in a year
    - I will also train a model to predict the value of QQQ in a month's time and see if I can use that to create an QQQ buy strategy that outcompetes a simple buy-and-hold strategy. That work will be done in the 4th notebook.

--------

Notes to self:

Okay, so I think I have a decent start here, but I have more work to do with the actual feature engineering.

Basically, I jumped passed that and made some models that seem to work surprisingly better than I would have guessed.
But now I should take a more serious look at the actual features and correct them as needed.
- Those that consistently increase (cpi, for eg) should most likely be converted to pct_change since it is often their rate of change that is more important anyways (quickly increasing cpi means high inflation)
- Those that hover around a mean can likely just be z-scored and they will be functional then.
- Those that have min value 0 but go up every now and then can prob be scaled so that their max is 1.
- 

After that, I can move all of the actual model building stuff to the next workbook. And do all of the model evaluation things.

---

In [47]:
import numpy as np
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

from macro_etf.common import PROCESSED_DATA_DIR, MODELLING_TARGETS

data_fn = "processed_market_data.csv"

### 3.1: Load data

In [48]:
df = pd.read_csv(PROCESSED_DATA_DIR / data_fn, index_col=0)
df.index = pd.to_datetime(df.index)
df.head()

            yield_spread  credit_spread  ...  volume_oil   real_gdp
2001-02-28          0.51           2.88  ...     82364.0  14229.765
2001-03-31          0.75           3.04  ...     63947.0  14183.120
2001-04-30          1.05           2.73  ...     40223.0  14183.120
2001-05-31          1.21           2.65  ...    101694.0  14183.120
2001-06-30          1.17           2.65  ...     86303.0  14271.694

[5 rows x 24 columns]

### 3.2: Define a feature matrix and prediction targets

In [49]:
# Let's start by defining the feature matrix as the entire unaltered feature set
X = df.copy()

for target, target_param in MODELLING_TARGETS.items():
    X[f'target_{target}'] = (
        X[target_param['variable']]
            .pct_change(periods=target_param['date_gap']) #Take the percent change as that is more informative for variables with a trend.
            .shift(periods=-target_param['date_gap']) #shift the variables so that they correspond to the date gap specified
    )

The features should be normalized / regularized / modified before being passed as training variables to a model. For example, those that trend upwards over time (e.g., cpi, retail sales, etc) can be handled poorly depending on choice of model. Also for these, what is often more important is the percent change of these features over time rather than just the raw number, e.g., an ETF increasing in value from 1 to 2 is a lot more interesting than an increase of 100 to 101. So, I will instead calculate the percent changes of these.

In [50]:
# The number of months between recordings of different features. gdp is quarterly and so the percent change will have to be over 3 months
trending_features_lags = {
    'cpi': 1,
    'retail_sales': 1,
    'm2': 1,
    'close_spy': 1,
    'close_qqq': 1,
    'close_oil': 1,
    'real_gdp': 3
}

for feat, lag in trending_features_lags.items():
    X[f'{feat}_percent_change'] = X[feat].pct_change(periods=lag)
    X = X.drop(feat, axis=1)

In [51]:
# Due to calculating percent changes and shifting, there will now be some nan entries at the end of the dataset. Let's remove them.
X = X.dropna()

In [52]:
# Display the results
display(X.head())
display(X.tail())

            yield_spread  ...  real_gdp_percent_change
2001-05-31          1.21  ...                -0.003278
2001-06-30          1.17  ...                 0.006245
2001-07-31          1.28  ...                 0.006245
2001-08-31          1.21  ...                 0.006245
2001-09-30          1.74  ...                -0.004006

[5 rows x 28 columns]

            yield_spread  ...  real_gdp_percent_change
2025-02-28          0.25  ...                 0.004599
2025-03-31          0.34  ...                -0.001625
2025-04-30          0.57  ...                -0.001625
2025-05-31          0.52  ...                -0.001625
2025-06-30          0.52  ...                 0.009460

[5 rows x 28 columns]

### 3.3 Split the data into training and test sets

In [54]:
# Let's split the data into training and test data
train_prop = 0.7
test_prop = 1.0 - train_prop
n_train = int(train_prop*X.shape[0])
n_test = X.shape[0] - n_train
train_inds = np.arange(0,n_train)
test_inds = np.arange(n_train, X.shape[0])


split_labels = ['train']*n_train + ['test']*n_test
X['split'] = split_labels

### 3.4: Regularize the features

In [ ]:
from sklearn.preprocessing import StandardScaler

# Train a scaler using the training dataset and then apply the scaler to both the training and test datasets
#   We do this split so that information contained in the training set isn't accidentally incorporated into the test set.
#   This can happen when calculating a feature's z-score if all values are used to calculate the mean and std.
#   I also need to be careful to not scale the target variables, as otherwise I will have to de-scale them and that would be annoying

target_cols = [col for col in X.columns if 'target' in col] + ['split']
non_target_cols = list (set(X.columns) - set(target_cols))

X_train = X.query('split == "train"')[non_target_cols]
X_test = X.query('split == "test"')[non_target_cols]
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = pd.DataFrame(
    scaler.transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)
X_test_scaled = pd.DataFrame(
    scaler.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)

X_scaled = pd.concat(
    [
        X_train_scaled, 
        X_test_scaled
    ], 
    axis=0
)
X_scaled = pd.concat(
    [X_scaled, X[target_cols]], axis=1
)

In [56]:
print(target_cols)
print(non_target_cols)

['target_gdp_3mo', 'target_gdp_12mo', 'target_qqq_1mo', 'target_qqq_3mo', 'split']
['close_qqq_percent_change', 'yield_spread', 'personal_savings_rate', 'fed_funds_rate', 'close_vix', 'cpi_percent_change', 'unemployment', 'financial_stress', 'close_oil_percent_change', 'consumer_sentiment', 'initial_claims', 'credit_spread', 'building_permits', 'close_spy_percent_change', 'real_gdp_percent_change', 'job_openings', 'volume_spy', 'housing_starts', 'volume_oil', 'industrial_production', 'volume_qqq', 'm2_percent_change', 'retail_sales_percent_change', 'credit_card_delinquency']

### 3.5: Save training / test datasets + target variables

In [57]:
#I'm going to try to keep things pandasy and output one big dataframe containing the required info.

# save_df_X = pd.concat([
#     X_train_scaled,
#     X_test_scaled
# ])

# save_df_y = pd.concat([
#     pd.DataFrame(y_train).assign(split='train'),
#     pd.DataFrame(y_test).assign(split='test')
# ])

# save_df = pd.concat([
#     save_df_X,
#     save_df_y,
# ], axis=1)

# save_df.to_csv(PROCESSED_DATA_DIR / 'feature_matrix.csv')
X_scaled.to_csv(PROCESSED_DATA_DIR / 'feature_matrix.csv')